
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 24 19:10:28 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int IDENT = 24;
  public static final int CLASS = 22;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 9;
  public static final int SEMI = 5;
  public static final int RETURN = 8;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 10;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int CHARCONST = 13;
  public static final int DIV = 21;
  public static final int PROG = 2;
  public static final int MINUS = 18;
  public static final int LSQUARE = 15;
  public static final int FINAL = 14;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int NEW = 20;
  public static final int RSQUARE = 16;
  public static final int VOID = 19;
}

